### ISSUE TITLE
Got error in chain service

### ISSUE THREAD

**Issue by AndyHod** [crustio/crust#345]
```
2020-12-05 06:04:33  ✨ Imported #1352506 (0x9f12…cd4f)
2020-12-05 06:04:38  💤 Idle (16 peers), best: #1352506 (0x9f12…cd4f), finalized #1352504 (0x5a3d…2df4), ⬇ 13.9kiB/s ⬆ 7.2kiB/s
2020-12-05 06:04:40  ✨ Imported #1352507 (0x65f9…2a55)
2020-12-05 06:04:41  ✨ Imported #1352506 (0x6144…352e)
2020-12-05 06:04:42  ✨ Imported #1352507 (0x47f6…3e44)
2020-12-05 06:04:43  💤 Idle (16 peers), best: #1352507 (0x65f9…2a55), finalized #1352505 (0xbbd6…ab4c), ⬇ 7.5kiB/s ⬆ 5.5kiB/s
2020-12-05 06:04:44  ✨ Imported #1352508 (0x3918…c433)
2020-12-05 06:04:45  ♻️  Reorg on #1352508,0x3918…c433 to #1352508,0xf1ca…affd, common ancestor #1352507,0x65f9…2a55
2020-12-05 06:04:45  ✨ Imported #1352508 (0xf1ca…affd)
2020-12-05 06:04:48  💤 Idle (16 peers), best: #1352508 (0xf1ca…affd), finalized #1352506 (0x9f12…cd4f), ⬇ 6.3kiB/s ⬆ 5.3kiB/s
2020-12-05 06:04:49  ✨ Imported #1352509 (0xb820…e7e7)
2020-12-05 06:04:53  💤 Idle (16 peers), best: #1352509 (0xb820…e7e7), finalized #1352506 (0x9f12…cd4f), ⬇ 7.9kiB/s ⬆ 8.0kiB/s
2020-12-05 06:04:58  💤 Idle (16 peers), best: #1352509 (0xb820…e7e7), finalized #1352507 (0x65f9…2a55), ⬇ 5.9kiB/s ⬆ 5.0kiB/s
2020-12-05 06:04:59  ✨ Imported #1352510 (0x8a52…3c02)
2020-12-05 06:05:03  💤 Idle (16 peers), best: #1352510 (0x8a52…3c02), finalized #1352508 (0xf1ca…affd), ⬇ 8.7kiB/s ⬆ 7.0kiB/s
2020-12-05 06:05:04  ✨ Imported #1352511 (0x1559…5249)
2020-12-05 06:05:08  💤 Idle (16 peers), best: #1352511 (0x1559…5249), finalized #1352509 (0xb820…e7e7), ⬇ 8.0kiB/s ⬆ 2.8kiB/s
2020-12-05 06:05:12  ♻️  Reorg on #1352511,0x1559…5249 to #1352511,0xa6e2…2ff5, common ancestor #1352510,0x8a52…3c02
2020-12-05 06:05:12  ✨ Imported #1352511 (0xa6e2…2ff5)
2020-12-05 06:05:13  💤 Idle (16 peers), best: #1352511 (0xa6e2…2ff5), finalized #1352509 (0xb820…e7e7), ⬇ 42.4kiB/s ⬆ 15.9kiB/s
2020-12-05 06:05:15  ✨ Imported #1352513 (0x0477…84d9)
2020-12-05 06:05:15  [0x99f0feefad745e67cb6f34fdc8f88ce3e867c8295c85d0daea9e2c08d6d62a7b] Extrinsic invalid
2020-12-05 06:05:15  [0xbc43874f6a76432d555a1c532bab4e9a36b70e3fff4ab5e78f99d06fe498a378] Extrinsic invalid
2020-12-05 06:05:15  [0xa884fb1f929a51707ba6382cd04896271e4887574d0d0c22010c083aff3ef7bb] Extrinsic invalid
2020-12-05 06:05:15  [0xbca01b3edd655b9066b40e831b90f5e3bd3dd1c36683ff225f7ad3b6c2b7da57] Extrinsic invalid
2020-12-05 06:05:15  [0x28d9d53a57f6a025d46a83009503ee069389f629518bd3dcdc27a4b70785c7c3] Extrinsic invalid
2020-12-05 06:05:18  💤 Idle (16 peers), best: #1352513 (0x0477…84d9), finalized #1352510 (0x8a52…3c02), ⬇ 12.4kiB/s ⬆ 10.0kiB/s
2020-12-05 06:05:22  ✨ Imported #1352514 (0x8395…d549)
2020-12-05 06:05:23  💤 Idle (16 peers), best: #1352514 (0x8395…d549), finalized #1352512 (0x029a…be9d), ⬇ 19.4kiB/s ⬆ 7.7kiB/s
2020-12-05 06:05:23  ♻️  Reorg on #1352514,0x8395…d549 to #1352514,0xa9a3…621a, common ancestor #1352513,0x0477…84d9
2020-12-05 06:05:23  ✨ Imported #1352514 (0xa9a3…621a)
2020-12-05 06:05:28  💤 Idle (15 peers), best: #1352514 (0xa9a3…621a), finalized #1352512 (0x029a…be9d), ⬇ 23.6kiB/s ⬆ 10.2kiB/s
2020-12-05 06:05:28  ✨ Imported #1352515 (0x9af4…7939)
2020-12-05 06:05:31  ♻️  Reorg on #1352515,0x9af4…7939 to #1352515,0x5ad5…3ab0, common ancestor #1352514,0xa9a3…621a
2020-12-05 06:05:31  ✨ Imported #1352515 (0x5ad5…3ab0)
2020-12-05 06:05:32  ✨ Imported #1352516 (0x256d…ac8f)
2020-12-05 06:05:33  💤 Idle (15 peers), best: #1352516 (0x256d…ac8f), finalized #1352513 (0x0477…84d9), ⬇ 7.1kiB/s ⬆ 4.6kiB/s
2020-12-05 06:05:38  💤 Idle (15 peers), best: #1352516 (0x256d…ac8f), finalized #1352514 (0xa9a3…621a), ⬇ 8.5kiB/s ⬆ 5.1kiB/s
2020-12-05 06:05:40  ✨ Imported #1352517 (0xf06c…864c)
2020-12-05 06:05:43  💤 Idle (15 peers), best: #1352517 (0xf06c…864c), finalized #1352514 (0xa9a3…621a), ⬇ 5.5kiB/s ⬆ 2.8kiB/s
2020-12-05 06:05:47  ✨ Imported #1352518 (0x5e1e…5df6)
2020-12-05 06:05:48  💤 Idle (15 peers), best: #1352518 (0x5e1e…5df6), finalized #1352515 (0x5ad5…3ab0), ⬇ 8.2kiB/s ⬆ 4.4kiB/s
2020-12-05 06:05:50  ✨ Imported #1352519 (0x495d…b0f5)
2020-12-05 06:05:53  💤 Idle (15 peers), best: #1352519 (0x495d…b0f5), finalized #1352516 (0x256d…ac8f), ⬇ 6.8kiB/s ⬆ 5.5kiB/s
2020-12-05 06:05:58  💤 Idle (15 peers), best: #1352519 (0x495d…b0f5), finalized #1352517 (0xf06c…864c), ⬇ 4.1kiB/s ⬆ 4.1kiB/s
2020-12-05 06:06:03  💤 Idle (15 peers), best: #1352519 (0x495d…b0f5), finalized #1352517 (0xf06c…864c), ⬇ 5.5kiB/s ⬆ 4.8kiB/s
2020-12-05 06:06:05  ✨ Imported #1352520 (0xb48e…5616)
2020-12-05 06:06:06  ♻️  Reorg on #1352520,0xb48e…5616 to #1352520,0x57af…f5b3, common ancestor #1352519,0x495d…b0f5
2020-12-05 06:06:06  ✨ Imported #1352520 (0x57af…f5b3)
2020-12-05 06:06:08  💤 Idle (15 peers), best: #1352520 (0x57af…f5b3), finalized #1352518 (0x5e1e…5df6), ⬇ 10.9kiB/s ⬆ 5.9kiB/s
2020-12-05 06:06:08  ✨ Imported #1352520 (0x6b19…b051)
2020-12-05 06:06:13  💤 Idle (15 peers), best: #1352520 (0x57af…f5b3), finalized #1352518 (0x5e1e…5df6), ⬇ 9.0kiB/s ⬆ 7.9kiB/s
2020-12-05 06:06:13  ♻️  Reorg on #1352520,0x57af…f5b3 to #1352521,0xab5b…611c, common ancestor #1352519,0x495d…b0f5
2020-12-05 06:06:13  ✨ Imported #1352521 (0xab5b…611c)
2020-12-05 06:06:15  ✨ Imported #1352522 (0xe54a…128f)
2020-12-05 06:06:18  💤 Idle (15 peers), best: #1352522 (0xe54a…128f), finalized #1352520 (0x6b19…b051), ⬇ 5.2kiB/s ⬆ 4.7kiB/s
2020-12-05 06:06:21  ✨ Imported #1352523 (0x8a43…94fd)
2020-12-05 06:06:23  💤 Idle (15 peers), best: #1352523 (0x8a43…94fd), finalized #1352520 (0x6b19…b051), ⬇ 2.5kiB/s ⬆ 2.3kiB/s
2020-12-05 06:06:28  💤 Idle (15 peers), best: #1352523 (0x8a43…94fd), finalized #1352521 (0xab5b…611c), ⬇ 11.1kiB/s ⬆ 7.4kiB/s
2020-12-05 06:06:32  ✨ Imported #1352524 (0xd3d6…bc1f)
2020-12-05 06:06:33  💤 Idle (15 peers), best: #1352524 (0xd3d6…bc1f), finalized #1352521 (0xab5b…611c), ⬇ 9.3kiB/s ⬆ 4.3kiB/s
2020-12-05 06:06:34  ✨ Imported #1352525 (0xc86f…2b60)
2020-12-05 06:06:38  💤 Idle (15 peers), best: #1352525 (0xc86f…2b60), finalized #1352523 (0x8a43…94fd), ⬇ 9.5kiB/s ⬆ 4.7kiB/s
2020-12-05 06:06:38  ✨ Imported #1352526 (0xf061…62bc)
2020-12-05 06:06:43  💤 Idle (15 peers), best: #1352526 (0xf061…62bc), finalized #1352524 (0xd3d6…bc1f), ⬇ 6.5kiB/s ⬆ 5.3kiB/s
2020-12-05 06:06:47  ✨ Imported #1352527 (0xa09b…ab7a)
2020-12-05 06:06:48  💤 Idle (15 peers), best: #1352527 (0xa09b…ab7a), finalized #1352524 (0xd3d6…bc1f), ⬇ 6.4kiB/s ⬆ 4.9kiB/s
2020-12-05 06:06:53  💤 Idle (15 peers), best: #1352527 (0xa09b…ab7a), finalized #1352525 (0xc86f…2b60), ⬇ 7.8kiB/s ⬆ 2.4kiB/s
2020-12-05 06:06:53  ✨ Imported #1352528 (0x2b40…a8b2)
2020-12-05 06:06:58  💤 Idle (16 peers), best: #1352528 (0x2b40…a8b2), finalized #1352526 (0xf061…62bc), ⬇ 6.0kiB/s ⬆ 5.1kiB/s
2020-12-05 06:07:00  👶 New epoch 13907 launching at block 0x5f17…f2cb (block slot 267858069 >= start slot 267858069).
2020-12-05 06:07:00  👶 Next epoch starts at slot 267858169
2020-12-05 06:07:01  ✨ Imported #1352529 (0x5f17…f2cb)
2020-12-05 06:07:02  💔 Error importing block 0xd4296c50090177d4cfb10a6bde38e318918e0d6df03c88328396fc8dbab4e059: Err(UnknownParent)
2020-12-05 06:07:03  💤 Idle (16 peers), best: #1352529 (0x5f17…f2cb), finalized #1352527 (0xa09b…ab7a), ⬇ 11.5kiB/s ⬆ 9.7kiB/s
2020-12-05 06:07:08  💤 Idle (16 peers), best: #1352529 (0x5f17…f2cb), finalized #1352528 (0x2b40…a8b2), ⬇ 8.8kiB/s ⬆ 3.4kiB/s
2020-12-05 06:07:13  💤 Idle (16 peers), best: #1352529 (0x5f17…f2cb), finalized #1352528 (0x2b40…a8b2), ⬇ 8.0kiB/s ⬆ 4.7kiB/s
2020-12-05 06:07:18  💤 Idle (16 peers), best: #1352529 (0x5f17…f2cb), finalized #1352528 (0x2b40…a8b2), ⬇ 1.7kiB/s ⬆ 1.0kiB/s
2020-12-05 06:07:23  💤 Idle (16 peers), best: #1352529 (0x5f17…f2cb), finalized #1352528 (0x2b40…a8b2), ⬇ 1.3kiB/s ⬆ 0.7kiB/s
2020-12-05 06:07:28  👶 New epoch 13907 launching at block 0x4b32…4563 (block slot 267858069 >= start slot 267858069).
2020-12-05 06:07:28  👶 Next epoch starts at slot 267858169
2020-12-05 06:07:28  💤 Idle (16 peers), best: #1352529 (0x5f17…f2cb), finalized #1352528 (0x2b40…a8b2), ⬇ 3.6kiB/s ⬆ 0.6kiB/s
2020-12-05 06:07:29  ♻️  Reorg on #1352529,0x5f17…f2cb to #1352529,0x4b32…4563, common ancestor #1352528,0x2b40…a8b2
2020-12-05 06:07:29  ✨ Imported #1352529 (0x4b32…4563)
2020-12-05 06:07:29  👴 Applying authority set change scheduled at block #1352529
2020-12-05 06:07:29  👴 Applying GRANDPA set change to new set with 60 authorities
2020-12-05 06:07:29  Re-finalized block #0x4b328c15572fc305e56f61c1f5b27de817f6e77b0b4171b7b3003015552b4563 (1352529) in the canonical chain, current best finalized is #135252

====================

Version: 0.10.2-26bf8bc-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/panicking.rs:595
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC>::import_justification
   6: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
   7: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
   8: sp_consensus::import_queue::import_single_block_metered
   9: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  10: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  11: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  14: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: std::thread::local::LocalKey<T>::with
  18: futures_executor::local_pool::block_on
  19: tokio::runtime::task::core::Core<T,S>::poll
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: tokio::runtime::task::raw::poll
  22: tokio::runtime::blocking::pool::Inner::run
  23: tokio::runtime::context::enter
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/alloc/src/boxed.rs:1318
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/alloc/src/boxed.rs:1318
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/sys/unix/thread.rs:71
  27: start_thread
  28: clone


Thread 'tokio-runtime-worker' panicked at 'returns Ok when no authority set change should be enacted; qed;', /opt/cache/git/checkouts/substrate-7e08433d4c370a21/668ecad/client

This is a bug. Please report it at:

        https://github.com/crustio/crust/issues/new

```

**Comment by zikunfan** [comment]
Transfer to substrate community @AndyHod

**Comment by MyronFanQiu** [comment]
Close it since we have upgrade to sb 3.0 and hope this issue should be solved already. If you meet this issue again, feel free to open a new issue.
