### ISSUE TITLE
owner节点报错，不能跑起来

### ISSUE THREAD

**Issue by peakhuang** [crustio/crust#846]
你好，我的owner报了下面的错误，提示是bug，请解决以下
2022-07-06 11:32:11  Crust    
2022-07-06 11:32:11  ✌️  version 1.2.0-f4a1014-x86_64-linux-gnu
2022-07-06 11:32:11  ❤️  by crustio, 2019-2022
2022-07-06 11:32:11  📋 Chain specification: Crust
2022-07-06 11:32:11  🏷 Node name: hf-owner-196000
2022-07-06 11:32:11  👤 Role: AUTHORITY
2022-07-06 11:32:11  💾 Database: RocksDb at /opt/crust/data/chain/chains/crust/db
2022-07-06 11:32:11  ⛓  Native runtime: crust-11 (crustio-crust-1.tx1.au1)
2022-07-06 11:32:11  🔨 Initializing Genesis block/state (state: 0x5628…607a, header-hash: 0x8b40…6a8c)
2022-07-06 11:32:11  👴 Loading GRANDPA authority set from genesis on what appears to be first startup.

====================

Version: 1.2.0-f4a1014-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:50:5
   7: raw_cpuid::CpuId::get_extended_feature_info
   8: cranelift_native::builder_with_backend_variant
   9: cranelift_native::builder
  10: wasmtime_jit::native::builder
  11: wasmtime::config::Config::new
  12: sc_executor_wasmtime::runtime::create_runtime
  13: sc_executor::wasm_runtime::create_wasm_runtime_with_code
  14: sc_executor::wasm_runtime::create_versioned_wasm_runtime
  15: sc_executor::wasm_runtime::RuntimeCache::with_instance
  16: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  17: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  18: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  19: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
  20: <alloc::sync::Arc<dyn sc_client_api::call_executor::ExecutorProvider<Block>+Executor = E> as sc_finality_grandpa::GenesisAuthoritySetProvider<Block>>::get
  21: sc_finality_grandpa::aux_schema::load_persistent
  22: sc_finality_grandpa::block_import_with_authority_set_hard_forks
  23: crust::service::new_partial
  24: crust::service::new_full
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  26: std::thread::local::LocalKey<T>::with
  27: tokio::runtime::thread_pool::ThreadPool::block_on
  28: tokio::runtime::context::enter
  29: tokio::runtime::Runtime::block_on
  30: sc_cli::runner::Runner<C>::run_node_until_exit
  31: crust::command::run
  32: crust::main
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: std::rt::lang_start::{{closure}}
  35: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panic.rs:396:14
      std::rt::lang_start_internal
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/rt.rs:51:25
  36: main
  37: __libc_start_main
  38: _start

Thread 'main' panicked at 'assertion failed: res.eax == 0', /opt/cache/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-8.1.2/src/lib.rs:295

This is a bug. Please report it at:

        https://github.com/crustio/crust/issues/new

**Comment by peakhuang** [comment]
重新安装操作系统18.04，这次没有将系统升级到18.04.6，然后再次安装crust的owner节点，配置好以后，启动owner节点，这次没有再报上面的错误，所以我分析，应该是crust目前的owner节点程序在18.04.6上有bug

**Comment by mmyyrroonn** [comment]
> 重新安装操作系统18.04，这次没有将系统升级到18.04.6，然后再次安装crust的owner节点，配置好以后，启动owner节点，这次没有再报上面的错误，所以我分析，应该是crust目前的owner节点程序在18.04.6上有bug

已知是在特定的cpu上的特定系统会出现这个问题，可能也跟内核有关

**Comment by peakhuang** [comment]
这个问题又出现了,在这个owner节点突然断电以后,再次启动以后,出现了这个问题,有解决的办法吗?

**Comment by jonathanudd** [comment]
Hello
I think we have this same problem on Ubuntu 22.04.
We have one node that is working but when deploying a new one it crashed when we set `--wasm-execution=compiled`
And without that argument the node syncs extremely slow.

Is there anything we can do to get around this?

```
Jan 26 09:29:47 juju-777782-0 polkadot[341126]: ====================
Jan 26 09:29:47 juju-777782-0 polkadot[341126]: Version: 1.2.0-f4a1014-x86_64-linux-gnu
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    0: sp_panic_handler::set::{{closure}}
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    1: std::panicking::rust_panic_with_hook
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:595:17
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    2: std::panicking::begin_panic_handler::{{closure}}
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:495:13
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:141:18
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    4: rust_begin_unwind
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:493:5
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    5: core::panicking::panic_fmt
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:92:14
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    6: core::panicking::panic
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:50:5
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    7: raw_cpuid::CpuId::get_extended_feature_info
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    8: cranelift_native::builder_with_backend_variant
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:    9: cranelift_native::builder
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   10: wasmtime_jit::native::builder
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   11: wasmtime::config::Config::new
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   12: sc_executor_wasmtime::runtime::create_runtime
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   13: sc_executor::wasm_runtime::create_wasm_runtime_with_code
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   14: sc_executor::wasm_runtime::create_versioned_wasm_runtime
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   15: sc_executor::wasm_runtime::RuntimeCache::with_instance
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::runtime_version
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   17: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sp_version::GetRuntimeVersion<Block>>::runtime_version
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   18: <sp_consensus::CanAuthorWithNativeVersion<T> as sp_consensus::CanAuthorWith<Block>>::can_author_with
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   19: <sc_consensus_babe::BabeVerifier<Block,Client,SelectChain,CAW> as sp_consensus::import_queue::Verifier<Block>>::verify
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   20: sp_consensus::import_queue::import_single_block_metered
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   23: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   24: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   26: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   27: <sc_service::task_manager::WithTelemetrySpan<T> as core::future::future::Future>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   28: std::thread::local::LocalKey<T>::with
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   29: futures_executor::local_pool::block_on
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   30: tokio::runtime::task::core::Core<T,S>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   32: tokio::runtime::task::harness::Harness<T,S>::poll
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   33: tokio::runtime::blocking::pool::Inner::run
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   34: tokio::runtime::context::enter
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   35: std::sys_common::backtrace::__rust_begin_short_backtrace
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   36: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   37: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/alloc/src/boxed.rs:1480:9
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/alloc/src/boxed.rs:1480:9
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:       std::sys::unix::thread::Thread::new::thread_start
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:              at rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys/unix/thread.rs:71:17
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   38: <unknown>
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:   39: <unknown>
Jan 26 09:29:47 juju-777782-0 polkadot[341126]: Thread 'tokio-runtime-worker' panicked at 'assertion failed: res.eax == 0', /opt/cache/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-8.1.2/src/lib.rs:295
Jan 26 09:29:47 juju-777782-0 polkadot[341126]: This is a bug. Please report it at:
Jan 26 09:29:47 juju-777782-0 polkadot[341126]:         https://github.com/crustio/crust/issues/new

```

**Comment by kate102066** [comment]
Hi @jonathanudd, has this issue been resolved later?

**Comment by jonathanudd** [comment]
> Hi [@jonathanudd](https://github.com/jonathanudd), has this issue been resolved later?

I think we copied the database from an existing node so we didn't really solve the issue no.
